name: update monkeytype stats
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: vnphanquang/monkeytype-readme@main
        with:
          monkeytype_api_key: ${{ secrets.MONKEYTYPE_API_KEY }}
          mode: time
          mode2: '60'
          style: flat-square
          label: monkeytype
